# $VERSION taken from CBICall

# User global variables: note the placeholders {} will be substituted in the Snakefile
datadir: "/media/mrueda/2TBS"
dbdir: "{datadir}/Databases"
ngsutils: "{datadir}/NGSutils"
tmpdir: "{datadir}/tmp"
mem: "8G"

# JAVA paths for different architectures
java:
  aarch64: "/usr/lib/jvm/java-8-openjdk-arm64/bin/java"
  amd64: "/usr/lib/jvm/java-8-openjdk-amd64/bin/java"

# Tools:
tools:
  aarch64:
    bwa: "{ngsutils}/bwa-0.7.18_arm64/bwa"
    samtools: "{ngsutils}/samtools-0.1.19_arm64/samtools"
    bedtools: "{ngsutils}/bedtools2_arm64/bin/bedtools"
  amd64:
    bwa: "{ngsutils}/bwa-0.7.18/bwa"
    samtools: "{ngsutils}/samtools-0.1.19/samtools"
    bedtools: "{ngsutils}/bedtools2/bin/bedtools"

# Commands for Picard and GATK. Placeholders will be replaced in the Snakefile.
picard: "{java} -Xmx{mem} -Djava.io.tmpdir={tmpdir} -jar {ngsutils}/picard/build/libs/picard.jar"
gatk: "{java} -Xmx{mem} -Djava.io.tmpdir={tmpdir} -jar {ngsutils}/gatk/3.5/GenomeAnalysisTK.jar"
mtoolboxdir: "{ngsutils}/MToolBox-master/MToolBox"

# GATK Bundle (hg19, b37)
bundle: "{dbdir}/GATK_bundle/b37"
ref: "{bundle}/references_b37_Homo_sapiens_assembly19.fasta"
refgz: "{bundle}/references_b37_Homo_sapiens_assembly19.fasta.gz"
dbsnp: "{dbdir}/dbSNP/human_9606_b144_GRCh37p13/All_20160408.vcf.gz"
mills_indels: "{bundle}/b37_Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
kg_indels: "{bundle}/b37_1000G_phase1.indels.b37.vcf.gz"
hapmap: "{bundle}/b37_hapmap_3.3.b37.vcf.gz"
omni: "{bundle}/b37_1000G_omni2.5.b37.vcf.gz"

# Training sets for variant recalibration
snp_res: >-
  -resource:hapmap,known=false,training=true,truth=true,prior=15.0 {hapmap} 
  -resource:omni,known=false,training=true,truth=false,prior=12.0 {omni} 
  -resource:dbsnp,known=true,training=false,truth=false,prior=6.0 {dbsnp}
indel_res: "-resource:mills,known=true,training=true,truth=true,prior=12.0 {mills_indels}"

# Exome target BED directory
exom: "{dbdir}/Agilent_SureSelect/hg19/bed"

# Parameters for UnifiedGenotyper
dcov: 1000
ug_call: 50
ug_emit: 10
